package timber

import (
	"fmt"
	"os"
	"runtime"
	"strings"
)

func CallerInfo(stackIndex int) string {
	file := ""
	line := 0
	ok := false

	_, file, line, ok = runtime.Caller(stackIndex)
	if !ok {
		// The breaks below failed to terminate the loop, and we ran off the
		// end of the call stack.
		return "unknown:0"
	}

	// This is a huge edge case, but it will panic if this is the case, see #180
	if file == "<autogenerated>" {
		return "unknown:0"
	}

	goPath := os.Getenv("GOPATH")
	parts := strings.Split(file, goPath+"/src/")
	file = parts[len(parts)-1]
	return fmt.Sprintf("%s:%d", file, line)
}
