// Code generated by gen/gen.go - DO NOT EDIT.
// This code can be regenerated by running the go generate below.
//go:generate make generated

package timber

import (
	"testing"
)

func TestTrace(t *testing.T) {
	Trace("test")
}

func TestTracef(t *testing.T) {
	Tracef("test %s", "format")
}

func TestTraceEx(t *testing.T) {
	TraceEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestLogger_Trace(t *testing.T) {
	New().Trace("test")
}

func TestLogger_Tracef(t *testing.T) {
	New().Tracef("test %s", "format")
}

func TestLogger_TraceEx(t *testing.T) {
	New().TraceEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestVerbose(t *testing.T) {
	Verbose("test")
}

func TestVerbosef(t *testing.T) {
	Verbosef("test %s", "format")
}

func TestVerboseEx(t *testing.T) {
	VerboseEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestLogger_Verbose(t *testing.T) {
	New().Verbose("test")
}

func TestLogger_Verbosef(t *testing.T) {
	New().Verbosef("test %s", "format")
}

func TestLogger_VerboseEx(t *testing.T) {
	New().VerboseEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestDebug(t *testing.T) {
	Debug("test")
}

func TestDebugf(t *testing.T) {
	Debugf("test %s", "format")
}

func TestDebugEx(t *testing.T) {
	DebugEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestLogger_Debug(t *testing.T) {
	New().Debug("test")
}

func TestLogger_Debugf(t *testing.T) {
	New().Debugf("test %s", "format")
}

func TestLogger_DebugEx(t *testing.T) {
	New().DebugEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestInfo(t *testing.T) {
	Info("test")
}

func TestInfof(t *testing.T) {
	Infof("test %s", "format")
}

func TestInfoEx(t *testing.T) {
	InfoEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestLogger_Info(t *testing.T) {
	New().Info("test")
}

func TestLogger_Infof(t *testing.T) {
	New().Infof("test %s", "format")
}

func TestLogger_InfoEx(t *testing.T) {
	New().InfoEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestWarning(t *testing.T) {
	Warning("test")
}

func TestWarningf(t *testing.T) {
	Warningf("test %s", "format")
}

func TestWarningEx(t *testing.T) {
	WarningEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestLogger_Warning(t *testing.T) {
	New().Warning("test")
}

func TestLogger_Warningf(t *testing.T) {
	New().Warningf("test %s", "format")
}

func TestLogger_WarningEx(t *testing.T) {
	New().WarningEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestError(t *testing.T) {
	Error("test")
}

func TestErrorf(t *testing.T) {
	Errorf("test %s", "format")
}

func TestErrorEx(t *testing.T) {
	ErrorEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestLogger_Error(t *testing.T) {
	New().Error("test")
}

func TestLogger_Errorf(t *testing.T) {
	New().Errorf("test %s", "format")
}

func TestLogger_ErrorEx(t *testing.T) {
	New().ErrorEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestCritical(t *testing.T) {
	Critical("test")
}

func TestCriticalf(t *testing.T) {
	Criticalf("test %s", "format")
}

func TestCriticalEx(t *testing.T) {
	CriticalEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestLogger_Critical(t *testing.T) {
	New().Critical("test")
}

func TestLogger_Criticalf(t *testing.T) {
	New().Criticalf("test %s", "format")
}

func TestLogger_CriticalEx(t *testing.T) {
	New().CriticalEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestFatal(t *testing.T) {
	Fatal("test")
}

func TestFatalf(t *testing.T) {
	Fatalf("test %s", "format")
}

func TestFatalEx(t *testing.T) {
	FatalEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}

func TestLogger_Fatal(t *testing.T) {
	New().Fatal("test")
}

func TestLogger_Fatalf(t *testing.T) {
	New().Fatalf("test %s", "format")
}

func TestLogger_FatalEx(t *testing.T) {
	New().FatalEx(map[string]interface{}{
		"thing": "stuff",
	}, "test")
}
